---
title: "Quick Links"
format: html
theme: darkly
editor: visual
---

+--------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
| ## Chi Square Mobile                                                                                               | ## Learning Analytics Apps (POCs)                                                    |
|                                                                                                                    |                                                                                      |
| -   [Chi Square Mobile: User Manual](https://chi2labs.github.io/mobile-manual/)                                    | -   [Activity Report Single Course](https://chi2.shinyapps.io/activityreport/)\      |
| -   [Kai++ (presentation)](https://chi2labs.github.io/mobile-manual/kai-plus-plus.html)                            |     Compatibility: Moodle, Savvas, Mobile, Unizin                                    |
|                                                                                                                    |                                                                                      |
| ## Presentations                                                                                                   | -   [Chi2 Learning Analytics for LMS](https://chi2.shinyapps.io/POC_chi2lms/)\       |
|                                                                                                                    |     Compatible with: Moodle, Savvas, Mobile, Unizin                                  |
| -   [Teaching Data Science in Adverse Circimstances](https://dietrichson.github.io/posit-conf-2023/#/title-slide)\ |                                                                                      |
|     Presentation Posit::Conf 2023.                                                                                 | -   [Instructor Dashboard](https://chi2.shinyapps.io/example_single_course/?p=home)\ |
|                                                                                                                    |     Instructor view of Chi2 Learning Analytics\                                      |
| ## Gatai - Gaturrín                                                                                                |     Compatible with: Moodle, Savvas, Mobile, Unizin                                  |
|                                                                                                                    |                                                                                      |
| -   [Gatai v. X-Mas-Tree](https://chi2labs.github.io/x-mas-3/q/)\                                                  | -   [Learning Analytics Unizin](https://chi2.shinyapps.io/unizin_demo/?)\            |
|     Write-up of Reinforcement Learning Project                                                                     |     Chi2 Learning Analytics for Unizin\                                              |
|                                                                                                                    |     Compatible with: Unizin                                                          |
| -   [Gaturrín](https://chi2labs.github.io/gaturrin): Presentation.                                                 |                                                                                      |
|                                                                                                                    | -   [Grade Prediction](https://chi2.shinyapps.io/predictive_demo/)\                  |
| -   [Tic Tac Toe - Gaturrín: Proof of Concept](https://chi2.shinyapps.io/tic-tac-toe/)\                            |     Predictive model with Local Model Evaluation (LME)\                              |
|     Compatible with: Chi2 Mobile App. GatAi                                                                        |     Compatible with: Unizin, Moodle                                                  |
|                                                                                                                    |                                                                                      |
| ## Moodle                                                                                                          |                                                                                      |
|                                                                                                                    |                                                                                      |
| -   [Moodle R: Helper functions to Analyze Moodle Data](https://chi2labs.github.io/moodleR/)                       |                                                                                      |
+--------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+
